FORMAT: 1A
HOST: http://localhost:3000/aggie/v1/


# TV Dashboard
TV dashboard API provides access to personalized tv content recommendation data.
Data provided by this API is normally presented in form of rows. Row, Content and 
VodCategory are main entities at recommendation dashboard API model. Row provides 
organization to Contents that is an actual presentation content of various types.
API is RESTfull by design featuring lowers the complexitiy of data aggregation, 
request count for consuming applications. That comes with price of having user
scope methods. 

Design starting points:
* Clients wants to load categories at module startup also with complete 
shelf list and all imediate Contents to switch them quickly. Later optimizations will 
emerge so API should provide more fine grained data returns now. 


Method call model:
API should isn't too chatty because of preloading required to achive UI snappines.
1. Fetch imediate data: Rows, Content, Search index (page 1), 
2. a. Fetch next page data: Content
2. b. Purchase options fetch
3. a. Similar content fetch


Notes on caching:
* Client Dashboard moduile caches dashboard data (case 1. from call model) 
inside lifecycle of an app. Outside dashboard module life data is not there to conserve
memory on STBs.


## Users recommendation profile [/{userId}/tvdashboard/profile]
+ Parameters
    + userId: `2342` (string)
    
### Get users recommendation profile [GET]
    
+ Response 200 (application/json)

        {
            "recommendationPersonalized": true,
            "isDashboardDefaultScreen": true ,
            "recommendationExplanation": true
        }
        
## Recommendation consent message [/{userId}/tvdashboard/consent{?language}]
+ Parameters
    + userId: `2342` (string)
    + language: `en` (string) - (Optional) Defaults to `en`.
    
### Get users recommendation profile [GET]
    
+ Response 200 (application/json)

        {
            "message": "Consent text here" 
        }


## Rows [/{userId}/tvdashboard/rows{?language}]
+ Parameters
    + language: `en` (string) - (Optional) Defaults to `en`  .

### List all Rows [GET]
Rows are returned completely in single response as data complexity is low and clients 
are expected to store them in same manner. Tag is unique identifier of cateroies then 
used for content fetching. Recommendation rank is denoted by order. First presented 
first in response. Titles are translated to english by default. 
NOTE on object reconstruction: 2 entites are delivered here that inherits from same
anchestor Row;
- Rows are denoted by type=contents.
- Categories are denoted by lack of type field. Leaf categories has no list field.

+ Response 200 (application/json)

        [
            {
              "tag": "for-me",
              "title": "For me"
              "type": "content"
            },
            {
              "tag": "my-content",
              "title": "My Content",
              "type": "content"
            },
            {
              "tag": "comedy",
              "title": "Comedy"
              "type": "content"
            },
            {
              "tag": "action",
              "title": "Action",
              "type": "content"
            },
            {
              "tag": "categories",
              "title": "Categories",
              "list": [
                {
                    "tag": "drama",
                    "title": "Drama",
                    "color:": "#aa00cc"
                },
                {
                    "tag": "scifi",
                    "title": "Drama",
                    "color:": "#aa11cc",
                    "list": [
                        {
                            "tag": "pero-dislikes",
                            "title": "Pero dislikes",
                            "color": "#aabb00"
                        },
                        {
                            "tag": "pero-dislikes-even-more",
                            "title": "Pero dislikes even more",
                            "color": "#aabb11"
                        }
                    ]
                },
                {
                    "tag": "cartoons",
                    "title": "Cartoons",
                    "color:": "#aacc00"
                }                
              ]
            }
        ]

## Row's list of contents  [/{userId}/tvdashboard/rows/{rowTag}/content{?page,pageSize,language}]
Lists content contained in some row. 

+ Parameters
    + userId: `2342` (string)
    + rowTag: `for-me` (string)
    + page: `2` (number) - (Optional) Returns some page.
    + pageSize: `10` (number) - (Optional) Defines page size from 1-50.
    + language: `en` (string) - (Optional) Defaults to `en`.

### List of contents [GET]

Method returns list of content to display forsome row. Results excludes genres and categories.
Recommendation rank is denoted by order. First presented, first in response. Response 
contains data needed for row view, short decription panel view and reference to next more
detailed call that brings all data needed for details screen, purchase making logic, etc. 
Row is referenced by unique rowTag. Entity IDs are unique for recoomendation dashboard 
purpose. Some fields are limited in length. 

Notes on object reconstruction:
- Entities shares common Content type fileds that are augumented with Show, Series and VoD child types. 
- Entities types are determined by type field.
- Fields anclosed within Content are always defined others are nullable.
- Image links are hashes that are concstructed from templates that are response enclosed.
- externalId is reference for call before content playout, purchase, etc...

+ Response 200 (application/json)

       
        {
            "list": [
                {
                    "id": "1001",
                    "type": "series",
                    "title": "House of Cards",
                    "description": "A Congressman works with his equally conniving wife to exact revenge on the people who betrayed him. //max 200 chars",
                    "poster": "<hash>",
                    "background": "<hash>",
                    "cast": "Kevin Spacey, Michel Gill, Robin Wright // max 50 chars",
                    "directors": "James Foley, Robin Wright //max 50 chars",
                    "year": 2016,
                    "country": "USA",
                    "genre": "drama, crime",
                    "duration": 3600,
                    "rating": {"age": 14, "imdb": 9.0, "user": 9.6},
                    "watched": true,
        
                    "recommendationExplanation": "Because you watched Something",
        
                    "series": {"season": 1, "episode": 1, "lastWatchedSeason": 2},
                    "subTitle": "Chapter 52",
                    "contentKey": "series-1001",
                    
                    "start": 1469544033000,
                    "channelId": 5001,
                    "channelIcon": "<hash>",
                    "chatchUpRecorded": true
                },
                {
                    "id": "1002",
                    "type": "show",
                    "title": "Plastik fantastik",
                    "description": "Odličen slovenski dokumentarec o plastiki z malo drugačnega zornega kota, njenih vplivih na vas in okolje.",
                    "poster": "<hash>",
                    "background": "<hash>",
                    "cast": "Uroš Robič, Žiga Čamernik",
                    "directors": "Uroš Robič, Miha Dulmin",
                    "year": 2013,
                    "country": "SI",
                    "genre": "drama",
                    "duration": 4140,
                    "rating": {"age": 0, "imdb": null, "user": 9.6},
                    "watched": true,
                    "resource": null,
                     
                    "recommendationExplanation": "Because you watched something",
        
                    "series": null,
                    "subTitle": null,
                    "contentKey": null,
        
                    "start": 1469544033000,
                    "channelId": 5001,
                    "channelIcon": "<hash>",
                    "chatchUpRecorded": true
                },
                {
                    "id": "1003",
                    "type": "vod",
                    "title": "Deadpool",
                    "description": "A former Special Forces operative turned mercenary is subjected to a rogue experiment that leaves him with accelerated healing powers, adopting the...",
                    "poster": "<hash>",
                    "background": "<hash>",
                    "cast": "Ryan Reynolds, Morena Baccarin, T.J. Miller",
                    "directors": "Tim Miller",
                    "year": 2016,
                    "country": "USA",
                    "genre": "action, adventure, comedy",
                    "duration": 6480,
                    "rating": {"age": 12, "imdb": 8.1, "user": 7.2},
                    "watched": false,
                    "resource": null,
                       
                    "recommendationExplanation": null,
        
                    "series": null,
                    "subTitle": null,
                    "contentKey": null,
                     
                    "start": null,
                    "channelId": null,
                    "channelIcon": null,
                    "chatchUpRecorded": null
                }
            ],
            "linkTemplates": {
                "poster": "http://hostnameA/images/{{hash}} //quality is determined by app, absolute URL",
                "background": "http://hostnameB/images/{{hash}} // see above",
                "channelIcon": "http://hostnameC/images/{{hash}} // see above"
            },
            "previousPageLink": "/aggie/1/tvdashboard/for-me/contents?language=si&page=1 //updated page parameters from request",
            "nextPageLink": "/aggie/1/tvdashboard/for-me/contents?language=si&page=3 // see above"
        }


## Content details [/{userId}/tvdashboard/rows/{rowTag}/contents/{id}{?language,sibling}]
Content details.

+ Parameters
    + userId: `2342` (string)
    + rowTag: `for-me` (string)
    + id: `2342` (string)
    + language: `en` (string) - (Optional) Defaults to `en`.
    + sibling: `next|previous` (string) - (Optional) Ignored by default.

### Content details [GET]
Method returns single Content's child types without some restrictions as long strings 
trimming and featuring extra fields. Method can return next or previous sibling of 
specified contents id.
Notes on parsing: 
- Additional field: productId, populated where there could be some entity from MW 
referenced. 


+ Response 200 (application/json)

       
        {
            "list": [
                {
                    "id": "1001",
                    "type": "series",
                    "title": "House of Cards",
                    "description": "A Congressman works with his equally conniving wife to exact revenge on the people who betrayed him.",
                    "poster": "<hash>",
                    "background": "<hash>",
                    "cast": "Kevin Spacey, Michel Gill, Robin Wright",
                    "directors": "James Foley, Robin Wright",
                    "year": 2016,
                    "country": "USA",
                    "genre": "drama, crime",
                    "duration": 3600,
                    "rating": {"age": 14, "imdb": 9.0, "user": 9.6},
                    "watched": true,
                    
                    "series": {"season": 3, "episode": 13, "lastWatchedSeason": 2},
                    "subTitle": "Chapter 52",
                    "contentKey": "series-1001",
                    
                    "recommendationExplanation": null,
                    
                    "start": 1469544033000,
                    "channelId": 5001,
                    "channelIcon": "<hash>",
                    "chatchUpRecorded": true
                    
                    "externalId": "31534"
                }
            ],
            "linkTemplates": {
                "poster": "http://hostnameA/images/{{hash}}",
                "background": "http://hostnameB/images/{{hash}}",
                "channelIcon": "http://hostnameC/images/{{hash}}"
            }
        }
        
+ Response 400

        {
            "error": 'language-is-unavailable-for-content',
            "message": 'Desired content has no translation in desired language.',
        }   
        
+ Response 400

        {
            "error": 'content-id-does-not-exist',
            "message": 'Desired content does not exits.',
        } 
        
+ Response 400

        {
            "error": 'next-sibling-doesn-not-exist',
            "message": 'Desired content has no next sibling.',
        }
        
+ Response 400

        {
            "error": 'previous-sibling-doesn-not-exist',
            "message": 'Desired content has no previous sibling.',
        }
        
        
        

## Users properites of an Content [/{userId}/tvdashboard/rows/{rowTag}/contents/{id}{?watched}]
Method updates various properies of a Content in users context. 

+ Parameters
    + userId: `2342` (string)
    + rowTag: `for-me` (string)
    + id: `2342` (string)
    + watched: true (boolean) - (Optional)
    
### Update properites of an Content [PUT]
    
+ Response 200 (application/json)

        {
            "sucess": true,
        }
 
 

## Search [/{userId}/tvdashboard/contents/search{?q,page,language}]
Search provides slimmed response as much as possible for quick transmision and parsing.

+ Parameters
    + q: `news` (String) - Return results for that includes serach results.
    + page: `1` (number) - (Optional) Results for page, 1 based.
    + language: `en` (string) - (Optional) Defaults to `en`.
    
### Search [GET]    
        
 + Response 200 (application/json)

        {
            "list": [
                {
                    "id": "1001",
                    "type": "series",
                    "title": "House of Cards",
                    "description": "A Congressman works with his equally conniving wife to exact revenge on the people who betrayed him.",
                    "duration": 3600,
                    "rating": {"age": 14, "imdb": 9.0, "user": 9.6},
                    "watched": true,
                    
                    "series": {"season": 3, "episode": 13, "lastWatchedSeason": 2},
                    "subTitle": "Chapter 52",
                    
                    "start": 1469544033000,
                    "channelId": 5001,
                    "channelIcon": "<hash>",
                    "chatchUpRecorded": true
                }
            ],
            "previousPageLink": "/aggie/1/tvdashboard/contents/search?language=si&page=1,
            "nextPageLink": "/aggie/1/tvdashboard/contents/search?language=si&page=3
        }